featured_lists:
  default: >-
    [{"title":"New Pms","length":5,"filter":"new", "tag":"", "link":"/my/messages/new", "solved":""},
    {"title":"Unread Pms","length":5,"filter":"unread", "tag":"", "link":"/my/messages/unread", "solved":""},
    {"title":"Sent Pms","length":5,"filter":"sent", "tag":"", "link":"/my/messages/sent", "solved":""},
    {"title":"Archived Pms","length":5,"filter":"archive", "tag":"", "link":"/my/messages/archive", "solved":""}]
  json_schema: '{
  "type": "array",
  "format": "table",
  "uniqueItems": true,
  "items": {
    "type": "object",
    "properties": {
      "title": {
        "type": "string",
        "description": "The list title"
      },
      "length": {
        "type": "string",
        "description": "Set the number of topics"
      },
      "filter": {
        "type": "string",
        "description": "Choose the type of PMs to show",
        "enum": [
          "latest",
          "archive",
          "sent",
          "new",
          "unread"
        ]
      },
      "tag": {
        "type": "string",
        "description": "Filter by tag name"
      },
      "link": {
        "type": "string",
        "description": "Where the list should link to"
      },
      "classname": {
        "type": "string",
        "description": "Set a CSS class name for custom styles"
      }
    },
    "additionalProperties": false
  }
}'
show_on:
  default: latest
  type: enum
  choices:
    - everywhere
    - homepage
    - custom
    - latest/top/new/categories
    - latest
    - categories
    - top
plugin_outlet:
  default: "above-main-container"

